repos:
  -   repo: local
      hooks:
        -   id: block-gradle-properties
            name: Block gradle.properties from being committed
            language: fail
            entry: "gradle.properties must not be committed — use gradle.example.properties instead"
            files: (^|/)gradle\.properties$
        -   id: block-todo-comments
            name: Block TODO / FIXME commented-out code
            language: pygrep
            entry: "TODO|todo|FIXME|fixme|HACK|hack|XXX|//\s*[Tt][Ee][Ss][Tt]|//\s*[Tt][Ee][Mm][Pp]"
            # MATCH : characters TODO, FIXME, HACK, XXX all  literally and non cases sensitive
            # Match any kind of invisible character between "//" and "test", same for "//" and "temp"
            files: \.(kt|java|groovy|kts)$
            # MATCH : characters kt, java, groovy, kts, all  literally and cases sensitive