services:
  app:
    build:
      context: .
      secrets:
        - gradle_props
    image: project1:latest
    environment:

      - APP_PORT=${APP_PORT:-42000}
      - EXPOSED_PORT=${EXPOSED_PORT:-43000}
    ports:
      - "${EXPOSED_PORT:-43000}:${APP_PORT:-42000}"
      # -VALUE is a bash variable substitution: if the variable is not set (or empty), the default value is used

# Secret declaration
secrets:
  gradle_props:
    file: ./gradle.properties