services:
  app:
    build:
      context: .
      secrets:
        - gradle_props
    image: project1:latest
    environment:
      - APP_PORT=${APP_PORT:-42000}
    ports:
      - "${EXPOSED_PORT:-43000}:${APP_PORT:-42000}"

secrets:
  gradle_props:
    file: ./gradle.properties