# HOME
# org.gradle.java.installations.auto-detect=false
# jdk_version=21

#WORK
org.gradle.java.installations.auto-detect=true
jdk_version=25

org.gradle.java.installations.auto-download=true

org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.caching=true


repsyUrl=
repsyUsername=
repsyPassword=

repsyUrl_WRONG=
repsyUsername_WRONG=
repsyPassword_WRONG=