# HOME
# org.gradle.java.installations.auto-detect=false
# jdk_version=25

#WORK
org.gradle.java.installations.auto-detect=true
jdk_version=25

org.gradle.java.installations.auto-download=true

org.gradle.configuration-cache=true
org.gradle.configuration-cache.parallel=true
org.gradle.caching=true


repsyUrl=https://example.com
#repsyRepoUsername=example_repsyRepoUsername
repsyRepoPassword=example_repsyRepoPassword

repsyUrl_WRONG=example_repsyUrl_WRONG
repsyUsername_WRONG=example_repsyUsername_WRONG
repsyPassword_WRONG=example_repsyPassword_WRONG

