name: Smoke Test CI

# Append on every push and pull-request on master branch
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    # Its NO a docker image. A runner is a complet VM. The VM from github run on Microsoft Azure cloud Ubuntu 24.04
    # Ubuntu 24.04  ubuntu-latest or ubuntu-24.04
    # https://github.com/actions/runner-images
    steps:
      - uses: actions/checkout@v4
        # This action checks-out repository under $GITHUB_WORKSPACE, so workflow can access it.

      # STEP 1 : Create gradle.properties from GH Secret
      - name: Create gradle.properties from secret
        run: echo "${{ secrets.GRADLE_PROPERTIES }}" > gradle.properties
        # What's inside ${{ }} is not plain text, it tells GA to evaluate it before passing the command to the shell
        # Enclosing characters in double-quotes ( "" ) shall preserve the literal value of all characters within the double-quotes, with the exception of the characters backquote, <dollar-sign>, and <backslash>

      # STEP 2 : Build image via compose (secrets handled in docker-compose.yml) and smoke test
      - name: Check /test endpoint to catch eventual port mismatch
        run: |
          # $(...) substitution, the output of the expression replace the expression
          # grep "exposedPort" gradle.properties | cut -d'=' -f2
          # Search the line containing "exposedPort" in gradle.properties
          # Pipe the line found then cut the line in fields on delimiter "=" and extract the 2nd field
          # field count created by cut command start at one
          # The first is a positive numbers separated by a <hyphen-minus> (low- high), which represents all fields from the first number to the second number.
          # The second is a positive number preceded by a <hyphen-minus> (- high), which represents all fields from field number 1 to that number.
          # The third is a positive number followed by a <hyphen-minus> ( low-), which represents that number to the last field, inclusive.
          export EXPOSED_PORT=$(grep "exposedPort" gradle.properties | cut -d'=' -f2)
          docker compose up -d --build
          curl --retry 10 --retry-delay 8 --retry-all-errors http://localhost:$EXPOSED_PORT/test
          docker compose down
          # A <backslash> that is not quoted shall preserve the literal value of the following character, with the exception of a <newline>. If a <newline> follows the <backslash>, the shell shall interpret this as line continuation.
          # "export" a value change it scope and make the value available for child process